services:
    schnoop-schema:
        build: .
        volumes:
            - .:/src
        links:
            - mysql
        command: bash
    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=slurp_testing
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
